language: node_js
node_js:
- '9.11'

cache:
  directories:
    - "node_modules"

script:
  - yarn test
  - yarn build
  - echo my-custom-domain.ru > build/CNAME

deploy:
  provider: pages
  github-token: 3d89827d8d0e7e0e03f3a28a116e62c65cf79caa
  committer-from-gh: true
  skip-cleanup: true
  keep-history: true
  local-dir: build
  repo: alembikovm
  target-branch: master
  on:
    branch: master
